#!/bin/sh

#This file is part of the TinyTools distribution (https://github.com/Calebe94/TinyTools).
#Copyright (C) 2021 TinyTools
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

####################################################################################################
# Variables used in the script.
####################################################################################################
DMENU_ARGS=$@
TBM=tbm
[ -z "$TBM_FILE" ] || [ "$TBM_FILE" = "/dev/stdout" ] && TBM_FILE=$HOME/.tbookmarks

get_bookmark_url()
{
    $TBM -l | grep "$1" | awk '{print $1}'
}

get_bookmark_id()
{
    $TBM -li | grep "$1" | awk '{print $1}' | rev | cut -c 2- | rev
}

bookmark_action()
{
    bookmark="$1"
    actions="[open]\n[copy]\n[delete]\n[back]\n[close]"
    selection=$(echo "$actions" | dmenu -p "$bookmark" $DMENU_ARGS)
    if [ ! -z "$selection" ]; then
        case "$selection" in
            "[open]")
                url=$(get_bookmark_url "$bookmark")
                [ -z "$url" ] && echo "No url given!" | dmenu -p "Error" $DMENU_ARGS || xdg-open "$url"
                ;;
            "[copy]")
                url=$(get_bookmark_url "$bookmark")
                echo "$url" | xclip -selection clipboard
                ;;
            "[delete]")
                choice=$(echo "no\nyes" | dmenu -p "Are you sure?" $DMENU_ARGS)
                if [ "$choice" = "yes" ]; then
                    id=$(get_bookmark_id "$bookmark")
                    [ -z "$id" ] && echo "No id given!" | dmenu -p "Error" $DMENU_ARGS || tbm -d "$id"
                else
                    bookmark_action "$bookmark"
                fi
                ;;
            "[back]") show_bookmarks ;;
            *) exit 0 ;;
        esac
    fi
}

list_bookmarks_titles()
{
    $TBM -lt
}

show_bookmarks()
{
    actions="[new]\n[close]\n"
    bookmarks="$actions$(list_bookmarks_titles)"
    selection=$(echo "$bookmarks" | dmenu -p "Bookmarks" $DMENU_ARGS)
    if [ ! -z "$selection" ]; then
        case "$selection" in
        "[new]")
            status=$($TBM "$(xclip -o -selection clipboard)")
            [ -z "$status" ] && echo "No url on clipboard!" | dmenu -p "Error" $DMENU_ARGS || echo "$status"
            ;;
        "[close]") exit 0 ;;
        *) bookmark_action "$selection" ;;
        esac
    fi
}

###################################################################################################
############################################## MAIN ###############################################
###################################################################################################

show_bookmarks
