#!/bin/sh

#This file is part of the TinyTools distribution (https://github.com/Calebe94/TinyTools).
#Copyright (C) 2021 TinyTools
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

####################################################################################################
# Variables used in the script.
####################################################################################################
DMENU_ARGS="$*"
TBM=tbm
DMENU_CMD="dmenu $DMENU_ARGS"
[ -z "$DMENU_ARGS" ] && DMENU_CMD="dmenu"

[ -z "$TBM_FILE" ] || [ "$TBM_FILE" = "/dev/stdout" ] && export TBM_FILE=$HOME/.tbookmarks

get_bookmark_url()
{
    $TBM -l | grep "$1" | awk '{print $1}'
}

get_bookmark_id()
{
    $TBM -li | grep "$1" | awk '{print $1}' | rev | cut -c 2- | rev
}

bookmark_action()
{
    bookmark="$1"
    actions="[open]\n[copy]\n[delete]\n[back]\n[close]"
    selection=$(echo "$actions" | /bin/sh -c "$DMENU_CMD -p '$bookmark'")
    if [ -n "$selection" ]; then
        case "$selection" in
            "[open]")
                url=$(get_bookmark_url "$bookmark")
                if [ -z "$url" ]; then
                    echo "No url given!" | /bin/sh -c "$DMENU_CMD -p 'Error'"
                else
                    xdg-open "$url"
                fi
                ;;
            "[copy]")
                url=$(get_bookmark_url "$bookmark")
                echo "$url" | xclip -selection clipboard
                ;;
            "[delete]")
                choice=$(printf "no\nyes" | /bin/sh -c "$DMENU_CMD -p 'Are you sure?'")
                if [ "$choice" = "yes" ]; then
                    id=$(get_bookmark_id "$bookmark")
                    if [ -z "$id" ]; then
                        echo "No id given!" | /bin/sh -c "$DMENU_CMD -p 'Error'"
                    else
                        tbm -d "$id"
                    fi
                else
                    bookmark_action "$bookmark"
                fi
                ;;
            "[back]") show_bookmarks ;;
            *) exit 0 ;;
        esac
    fi
}

list_bookmarks_titles()
{
    $TBM -lt
}

convert_url_to()
{
    mode="$1"
    export TBM_FILE=/dev/stdout;
    url="$(xclip -o -selection clipboard)"
    case "$mode" in
        "md")
            tbm --md "$url" | xclip -selection clipboard
            notify-send "Converted $url" "to Markdown!"
            ;;
        "html")
            tbm --html "$url" | xclip -selection clipboard
            notify-send "Converted $url" "to HTML!"
            ;;
        "org")
            tbm --org "$url" | xclip -selection clipboard
            notify-send "Converted $url" "to Org Mode!"
            ;;
        *)  exit 1;;
    esac
}

show_bookmarks()
{
    actions="[new]\n[to md]\n[to html]\n[to org]\n[close]\n"
    bookmarks="$actions$(list_bookmarks_titles)"
    selection=$(echo "$bookmarks" | /bin/sh -c "$DMENU_CMD -p 'Bookmarks'")
    if [ -n "$selection" ]; then
        case "$selection" in
        "[new]")
            status=$($TBM "$(xclip -o -selection clipboard)")
            if [ -z "$status" ]; then
                echo "No url on clipboard!" | /bin/sh -c "$DMENU_CMD -p 'Error'"
            else
                echo "$status"
            fi
            ;;
        "[to md]") convert_url_to "md" ;;
        "[to html]") convert_url_to "html" ;;
        "[to org]") convert_url_to "org" ;;
        "[close]") exit 0 ;;
        *) bookmark_action "$selection" ;;
        esac
    fi
}

###################################################################################################
############################################## MAIN ###############################################
###################################################################################################

show_bookmarks
