#!/bin/bash

#This file is part of the TinyTools distribution (https://github.com/Calebe94/TinyTools).
#Copyright (C) 2021 TinyTools
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.

usage()
{
    echo "usage:"
    echo "tbkmk http://web.link"
}

create_bookmark()
{
    url="$1"
    title=$(curl -s "$url" | shup -r "title")
    printf "%s %s\n" "$url" "$title" | head -1
}

main()
{
    [ -z $TBKMK_FILE ] && TBKMK_FILE=$HOME/.tbookmarks
    create_bookmark "$1" | tee -a $TBKMK_FILE
}

main "$1"
