#!/bin/bash

#This file is part of the TinyTools distribution (https://github.com/Calebe94/TinyTools).
#Copyright (C) 2021 TinyTools
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.

url_regex='^(https?|ftp|file)://[-A-Za-z0-9\+&@#/%?=~_|!:,.;]*[-A-Za-z0-9\+&@#/%=~_|]$'
action=""
filter=""
url=""

usage()
{
    echo "usage: tbkmk {URL | OPTION}"
    echo "e.g: tbkmk http://web.link"
    echo "options:"
    echo "-l: lists bookmarks in \$TBKMK_FILE;"
    echo "-h: shows this usage message"
}

create_bookmark()
{
    url="$1"
    title=$(curl -s "$url" | shup -r "title")
    printf "%s %s\n" "$url" "$title" | head -1
}

list_bookmarks()
{
    cat $TBKMK_FILE
}

parse_arguments()
{
    while getopts "hlf:" args; do
        case "${args}" in
            l) action="list" ;;
            f) filter="${OPTARG}" ;;
            h | *) usage ;;
        esac
    done

    if [ ! "$#" -eq 0 ] && [[ $@ =~ $url_regex ]] && [ -z $action ]; then
        action="add"
        url="$@"
    fi
}

main()
{
    parse_arguments $@
    case "$action" in
        "list") [ -z $filter ] && list_bookmarks || grep "$filter" $TBKMK_FILE ;;
        "add") create_bookmark "$url" | tee -a $TBKMK_FILE ;;
    esac
}

[ -z $TBKMK_FILE ] && TBKMK_FILE=$HOME/.tbookmarks

if (($# == 0)); then
    list_bookmarks
    exit 0
fi

main $@
