#!/bin/bash

#This file is part of the TinyTools distribution (https://github.com/Calebe94/TinyTools).
#Copyright (C) 2021 TinyTools
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.

url_regex='^(https?|ftp|file)://[-A-Za-z0-9\+&@#/%?=~_|!:,.;]*[-A-Za-z0-9\+&@#/%=~_|]$'
action=""
filter=""
url=""
list_by=tee

usage()
{
    echo "usage: tbm {URL | OPTION}"
    echo "e.g: tbm http://web.link"
    echo "options:"
    echo "-l: lists bookmarks in \$TBM_FILE;"
    echo "-h: shows this usage message"
}

create_bookmark()
{
    url="$1"
    title=$(curl -s "$url" | shup -r "title")
    printf "%s %s\n" "$url" "$title" | head -1
}

list_bookmarks()
{
    cat $TBM_FILE
}

list_bookmarks_with_filter()
{
    filter="$1"
    grep "$filter" $TBM_FILE
}

list_by_title()
{
    awk '{$1=""; print $0}' | cut -c2-
}

list_by_url()
{
    awk '{print $1}'
}

parse_arguments()
{
    while getopts "hlf:tu" args; do
        case "${args}" in
            l) action="list" ;;
            f) filter="${OPTARG}" ;;
            t) list_by=list_by_title ;;
            u) list_by=list_by_url ;;
            h) usage; exit 0 ;;
            *) usage; exit 1 ;;
        esac
    done

    if [ ! "$#" -eq 0 ] && [[ $@ =~ $url_regex ]] && [ -z $action ]; then
        action="add"
        url="$@"
    fi
}

main()
{
    parse_arguments $@
    case "$action" in
        "list")
            if [ -z $filter ]; then
                list_bookmarks | ${list_by}
            else
                list_bookmarks_with_filter "$filter" | ${list_by}
            fi
            ;;
        "add") create_bookmark "$url" | tee -a $TBM_FILE ;;
    esac
}

[ -z $TBM_FILE ] && TBM_FILE=$HOME/.tbookmarks

if (($# == 0)); then
    list_bookmarks
    exit 0
fi

main $@
