#!/bin/bash

#This file is part of the TinyTools distribution (https://github.com/Calebe94/TinyTools).
#Copyright (C) 2021 TinyTools
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.

to_html()
{
    awk '{
        out=""
        for(i=2; i<=NF; i++)
        {
            out=out$i" "
        }
        printf "<a href=\"%s\">", $1
        printf "%s</a>", out
        printf "\n"
    }'
}

while read -r line
do
    echo "$line" | to_html
done < "${1:-/dev/stdin}"

